export default {
    path:"/movie",
    component:()=>import("@/views/Movie"),
    children:[
        {
            path:"city",
            component:()=>import("@/components/City")
        },
        {
            path:"nowplaying",
            component:()=>import("@/components/NowPlaying")
        },
        {
            path:"comesoon",
            component:()=>import("@/components/ComeSoon")
        },
        {
            path:"search",
            component:()=>import("@/components/Search")
        },
        {
            path:"/movie",
            redirect:"/movie/nowplaying"
        }
    ]
}